//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.home.remote.hello.api;

public class NotValidArgument extends com.zeroc.Ice.UserException
{
    public NotValidArgument()
    {
        this.message = "";
    }

    public NotValidArgument(Throwable cause)
    {
        super(cause);
        this.message = "";
    }

    public NotValidArgument(String message)
    {
        this.message = message;
    }

    public NotValidArgument(String message, Throwable cause)
    {
        super(cause);
        this.message = message;
    }

    public String ice_id()
    {
        return "::hello::api::NotValidArgument";
    }

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::hello::api::NotValidArgument", -1, true);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 8114034044150917005L;
}
